# Generated by Django 2.1.5 on 2019-01-30 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privilege',
            options={'verbose_name': 'Privilege', 'verbose_name_plural': 'Privileges'},
        ),
        migrations.AlterModelOptions(
            name='usermanagement',
            options={'verbose_name': 'User Management', 'verbose_name_plural': 'Users Management'},
        ),
        migrations.AlterModelOptions(
            name='usertype',
            options={'verbose_name': 'User Type', 'verbose_name_plural': 'User Types'},
        ),
        migrations.RenameField(
            model_name='usertype',
            old_name='user_type',
            new_name='name',
        ),
    ]
