# Generated by Django 2.1.5 on 2019-02-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgt', '0004_userrole_is_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermanagement',
            old_name='user_role',
            new_name='role',
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='mobile_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='bo/profile_picture'),
        ),
    ]
