# Generated by Django 2.1.5 on 2019-02-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgt', '0005_auto_20190208_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
