# Generated by Django 2.1.5 on 2019-02-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgt', '0006_auto_20190208_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanagement',
            name='role',
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='role',
            field=models.ManyToManyField(db_index=True, null=True, to='user_mgt.UserRole'),
        ),
    ]
