# Generated by Django 2.1.5 on 2019-02-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsdata',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True),
        ),
    ]
