# Generated by Django 2.1.5 on 2019-02-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_mgt', '0002_auto_20190201_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdata',
            name='crated_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='timestamp',
            field=models.CharField(db_index=True, max_length=60),
        ),
    ]
