# Generated by Django 2.1.5 on 2019-02-04 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_mgt', '0003_auto_20190201_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpsdata',
            old_name='crated_date',
            new_name='created_date',
        ),
    ]
