# Generated by Django 2.1.5 on 2019-02-21 03:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_mgt', '0005_auto_20190204_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.CharField(db_index=True, max_length=15)),
                ('latitude', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('longitude', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('status_vehicle', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('status_engine', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('mileage', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('created_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('timestamp', models.CharField(blank=True, db_index=True, max_length=60, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
