# Generated by Django 2.1.5 on 2019-02-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_mgt', '0006_lastlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpressionGpsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=500)),
                ('license_no', models.CharField(db_index=True, max_length=15)),
                ('latitude', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('longitude', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('status_vehicle', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('status_engine', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('mileage', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('created_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('timestamp', models.CharField(blank=True, db_index=True, max_length=60, null=True)),
            ],
        ),
    ]
