# Generated by Django 2.1.5 on 2019-02-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_mgt', '0007_impressiongpsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastlocation',
            name='address',
            field=models.CharField(db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='impressiongpsdata',
            name='address',
            field=models.CharField(db_index=True, max_length=500, null=True),
        ),
    ]
