# Generated by Django 2.1.5 on 2019-02-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_mgt', '0008_auto_20190225_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpsDailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('mileage', models.IntegerField()),
                ('viewer', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='impressiongpsdata',
            name='city',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lastlocation',
            name='city',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
