# Generated by Django 2.1.5 on 2019-02-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_mgt', '0009_auto_20190225_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressiongpsdata',
            name='pos_code',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lastlocation',
            name='pos_code',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
