# Generated by Django 2.1.5 on 2019-02-25 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_mgt', '0010_auto_20190225_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impressiongpsdata',
            old_name='pos_code',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='lastlocation',
            old_name='pos_code',
            new_name='postal_code',
        ),
    ]
