# Generated by Django 2.1.5 on 2019-02-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_mgt', '0011_auto_20190225_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdailyreport',
            name='campaign_name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gpsdata',
            name='campaign_name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='impressiongpsdata',
            name='campaign_name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lastlocation',
            name='campaign_name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
