# Generated by Django 2.1.5 on 2019-03-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_mgt', '0013_auto_20190228_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsdata',
            name='timestamp',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='impressiongpsdata',
            name='latitude',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='impressiongpsdata',
            name='longitude',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='impressiongpsdata',
            name='mileage',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='impressiongpsdata',
            name='timestamp',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='lastlocation',
            name='latitude',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='lastlocation',
            name='longitude',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='lastlocation',
            name='mileage',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='lastlocation',
            name='timestamp',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
