# Generated by Django 2.1.5 on 2019-03-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_mgt', '0014_auto_20190301_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdailyreport',
            name='license_no',
            field=models.CharField(db_index=True, max_length=15, null=True),
        ),
    ]
