# Generated by Django 2.1.5 on 2019-03-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_mgt', '0015_gpsdailyreport_license_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsdailyreport',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gpsdailyreport',
            name='viewer',
            field=models.IntegerField(default=0),
        ),
    ]
