# Generated by Django 2.1.5 on 2019-03-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_mgt', '0016_auto_20190301_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default='', max_length=255)),
                ('license_no', models.CharField(db_index=True, max_length=15)),
            ],
        ),
    ]
