# Generated by Django 2.1.5 on 2019-04-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_mgt', '0018_auto_20190306_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyGps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.CharField(db_index=True, max_length=15)),
                ('latitude', models.CharField(blank=True, max_length=55, null=True)),
                ('longitude', models.CharField(blank=True, max_length=55, null=True)),
                ('created_date', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
    ]
