# Generated by Django 2.1.5 on 2019-05-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_mgt', '0019_dummygps'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummygps',
            name='campaign_name',
            field=models.CharField(db_index=True, default='', max_length=15),
        ),
    ]
