# Generated by Django 2.1.5 on 2019-05-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_mgt', '0020_dummygps_campaign_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastDummyGps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.CharField(db_index=True, max_length=15)),
                ('latitude', models.CharField(blank=True, max_length=55, null=True)),
                ('longitude', models.CharField(blank=True, max_length=55, null=True)),
                ('mileage', models.CharField(blank=True, max_length=55, null=True)),
                ('created_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('campaign_name', models.CharField(db_index=True, default='', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='dummygps',
            name='mileage',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
