# Generated by Django 2.1.5 on 2019-02-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='ad_installation_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='ad_request_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
