# Generated by Django 2.1.5 on 2019-01-30 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Driver', 'verbose_name_plural': 'Drivers'},
        ),
    ]
