# Generated by Django 2.1.5 on 2019-02-07 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('driver_mgt', '0002_auto_20190207_0411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='name',
            new_name='real_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='bank_account_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='bank_branch_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='driver',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.BankAccount'),
        ),
    ]
