# Generated by Django 2.1.5 on 2019-02-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_mgt', '0003_auto_20190207_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
