# Generated by Django 2.1.5 on 2019-02-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_mgt', '0005_auto_20190208_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='email',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='real_name',
        ),
        migrations.AddField(
            model_name='driver',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='driver',
            name='mobile_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='driver/profile_picture'),
        ),
    ]
