# Generated by Django 2.1.5 on 2019-02-12 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area_db', '0002_auto_20190207_0852'),
        ('driver_mgt', '0006_auto_20190208_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='kelurahan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='area_db.Kelurahan'),
        ),
    ]
