# Generated by Django 2.1.5 on 2019-02-21 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver_mgt', '0007_driver_kelurahan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='driver',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='area_db.City'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='kecamatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='area_db.Kecamatan'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='kelurahan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='area_db.Kelurahan'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='mobile_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
