# Generated by Django 2.1.5 on 2019-05-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_mgt', '0008_auto_20190221_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuktiTayang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.CharField(default='', max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='driver/ktp_photo')),
                ('created_date', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
    ]
