# Generated by Django 2.1.5 on 2019-02-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
