# Generated by Django 2.1.5 on 2019-02-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=30)),
                ('bank_branch_name', models.CharField(max_length=30)),
                ('bank_account_number', models.CharField(max_length=30)),
                ('bank_account_name', models.CharField(max_length=50)),
                ('on_behalf', models.CharField(max_length=50)),
            ],
        ),
    ]
