# Generated by Django 2.1.5 on 2019-02-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20190220_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_branch_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='on_behalf',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
