# Generated by Django 2.1.5 on 2019-01-29 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area_db', '0001_initial'),
        ('vehicle_mgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('campaign_start_date', models.DateTimeField(blank=True)),
                ('campaign_end_date', models.DateTimeField(blank=True)),
                ('publish_start_date', models.DateTimeField(blank=True)),
                ('publish_end_date', models.DateTimeField(blank=True)),
                ('installation_start_date', models.DateTimeField(blank=True)),
                ('installation_end_date', models.DateTimeField(blank=True)),
                ('minimum_milage', models.IntegerField()),
                ('minimum_payment', models.IntegerField()),
                ('special_campaign_point', models.IntegerField()),
                ('terms_and_conditions', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=15)),
                ('no_of_vehicle', models.IntegerField()),
                ('installation_address', models.CharField(max_length=255)),
                ('campaign_picture', models.ImageField(blank=True, upload_to='campaign/campaign_picture')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='area_db.City')),
            ],
        ),
        migrations.CreateModel(
            name='GpsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='StickerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleOnCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_installation_schedule', models.DateTimeField(blank=True)),
                ('sticker_installation_schedule', models.DateTimeField(blank=True)),
                ('status', models.CharField(max_length=15)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign_mgt.Campaign')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_mgt.Vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='gps_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign_mgt.GpsType'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='area_db.Province'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sticker_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign_mgt.StickerType'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='vehicle_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_mgt.VehicleColor'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='vehicle_models',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_mgt.VehicleModel'),
        ),
    ]
