# Generated by Django 2.1.5 on 2019-02-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_mgt', '0001_initial'),
        ('campaign_mgt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='no_of_vehicle',
            new_name='amount_of_vehicle',
        ),
        migrations.RemoveField(
            model_name='vehicleoncampaign',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='vehicleoncampaign',
            name='vehicle',
            field=models.ManyToManyField(to='vehicle_mgt.Vehicle'),
        ),
    ]
