# Generated by Django 2.1.5 on 2019-01-30 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='gpstype',
            options={'verbose_name': 'GPS Type', 'verbose_name_plural': 'GPS Types'},
        ),
        migrations.AlterModelOptions(
            name='stickertype',
            options={'verbose_name': 'Sticker Type', 'verbose_name_plural': 'Sticker Types'},
        ),
        migrations.AlterModelOptions(
            name='vehicleoncampaign',
            options={'verbose_name': 'Vehicle Campaign', 'verbose_name_plural': 'Vehicles on Campaign'},
        ),
    ]
