# Generated by Django 2.1.5 on 2019-02-04 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_mgt', '0001_initial'),
        ('campaign_mgt', '0002_auto_20190204_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleoncampaign',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='vehicleoncampaign',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_mgt.Vehicle'),
        ),
    ]
