# Generated by Django 2.1.5 on 2019-02-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_mgt', '0005_auto_20190207_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_sticker_before', models.ImageField(blank=True, upload_to='campaign/campaign_installation_picture')),
                ('photo_sticker_after', models.ImageField(blank=True, upload_to='campaign/campaign_installation_picture')),
                ('photo_gps_before', models.ImageField(blank=True, upload_to='campaign/campaign_installation_picture')),
                ('photo_gps_after', models.ImageField(blank=True, upload_to='campaign/campaign_installation_picture')),
                ('photo_odometer', models.ImageField(blank=True, upload_to='campaign/campaign_installation_picture')),
                ('photo_form_installation', models.ImageField(blank=True, upload_to='campaign/campaign_installation_picture')),
                ('photo_form_uninstallation', models.ImageField(blank=True, upload_to='campaign/campaign_installation_picture')),
                ('gps_status', models.BooleanField(default=False)),
            ],
        ),
    ]
