# Generated by Django 2.1.5 on 2019-02-07 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_mgt', '0006_campaigninstallation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleoncampaign',
            name='installation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign_mgt.CampaignInstallation'),
        ),
    ]
