# Generated by Django 2.1.5 on 2019-03-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_mgt', '0008_auto_20190207_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='city',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='installation_end_date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='installation_start_date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='province',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='publish_end_date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='publish_start_date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='status',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='advertiser',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='agen',
            field=models.CharField(default='ABPluss', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='special_campaign_point',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='vehicle_brand',
        ),
        migrations.AddField(
            model_name='campaign',
            name='vehicle_brand',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='vehicle_color',
        ),
        migrations.AddField(
            model_name='campaign',
            name='vehicle_color',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='vehicle_model',
        ),
        migrations.AddField(
            model_name='campaign',
            name='vehicle_model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='campaign',
            name='vehicle_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
