# Generated by Django 2.1.5 on 2019-03-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_mgt', '0009_auto_20190301_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleoncampaign',
            name='gps_installation_schedule',
        ),
        migrations.RemoveField(
            model_name='vehicleoncampaign',
            name='installation',
        ),
        migrations.RemoveField(
            model_name='vehicleoncampaign',
            name='sticker_installation_schedule',
        ),
        migrations.RemoveField(
            model_name='vehicleoncampaign',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='vehicleoncampaign',
            name='vehicle_domisili',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicleoncampaign',
            name='vehicle_license_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicleoncampaign',
            name='vehicle_model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleoncampaign',
            name='campaign',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
