# Generated by Django 2.1.5 on 2019-01-29 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area_db', '0001_initial'),
        ('driver_mgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.CharField(max_length=15)),
                ('vehicle_year', models.CharField(max_length=4)),
                ('vehicle_used_for', models.CharField(max_length=30)),
                ('daily_main_route', models.CharField(max_length=255)),
                ('stnk_photo', models.ImageField(blank=True, upload_to='vehicle/stnk_photo')),
                ('front_side_photo', models.ImageField(blank=True, upload_to='vehicle/front_side_photo')),
                ('status', models.CharField(max_length=15)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver_mgt.Driver')),
                ('vehicle_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='area_db.City')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('vehicle_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_mgt.VehicleBrand')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='vehicle_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_mgt.VehicleType'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_mgt.VehicleColor'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_kecamatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='area_db.Kecamatan'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_mgt.VehicleModel'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='area_db.Province'),
        ),
    ]
