# Generated by Django 2.1.5 on 2019-01-30 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AlterModelOptions(
            name='vehiclebrand',
            options={'verbose_name': 'Vehicle Brand', 'verbose_name_plural': 'Vehicle Brands'},
        ),
        migrations.AlterModelOptions(
            name='vehiclecolor',
            options={'verbose_name': 'Vehicle Color', 'verbose_name_plural': 'Vehicle Colors'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'verbose_name': 'Vehicle Model', 'verbose_name_plural': 'Vehicle Models'},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'verbose_name': 'Vehicle Type', 'verbose_name_plural': 'Vehicle Types'},
        ),
    ]
