# Generated by Django 2.1.5 on 2019-02-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_mgt', '0002_auto_20190207_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='daily_main_route',
            field=models.TextField(),
        ),
    ]
