# Generated by Django 2.1.5 on 2019-02-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_mgt', '0004_auto_20190207_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vehicle Year',
                'verbose_name_plural': 'Vehicle Years',
            },
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='daily_main_route',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_used_for',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_mgt.VehicleYear'),
        ),
    ]
