# Generated by Django 2.1.5 on 2019-02-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_mgt', '0007_auto_20190212_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_color',
            field=models.CharField(default='', max_length=255),
        ),
    ]
