# Generated by Django 2.1.5 on 2019-02-13 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_mgt', '0008_auto_20190212_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='vehicle_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_mgt.VehicleBrand'),
        ),
    ]
