# Generated by Django 2.1.5 on 2019-02-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_mgt', '0010_remove_vehiclemodel_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_kecamatan',
        ),
    ]
