# Generated by Django 2.1.5 on 2019-01-30 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='kecamatan',
            options={'verbose_name': 'Kecamatan', 'verbose_name_plural': 'Kecamatan'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'Province', 'verbose_name_plural': 'Provinces'},
        ),
    ]
