# Generated by Django 2.1.5 on 2019-02-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_db', '0002_auto_20190207_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'MainRoute',
                'verbose_name_plural': 'MainRoutes',
            },
        ),
    ]
